### ISSUE TITLE
RuntimeError: non-empty 3D or 4D input tensor expected but got ndim: 4

### ISSUE THREAD

**Issue by liangsiping2019** [haotian-liu/yolact_edge#41] opened 2021-01-27 05:09 UTC
the error:RuntimeError: non-empty 3D or 4D input tensor expected but got ndim: 4

**Comment by haotian-liu** [comment] 2021-01-27 05:12
Can you provide the full error log with the command you are using?

**Comment by liangsiping2019** [comment] 2021-01-27 05:15
I use this command: "python eval.py --trained_model=weights/yolact_edge_54_800000.pth --benchmark --max_images=1000" 
the print contents:
python eval.py --trained_model=weights/yolact_edge_54_800000.pth --benchmark --max_images=1000
Config not specified. Parsed yolact_edge_config from the file name.

loading annotations into memory...
Done (t=1.55s)
creating index...
index created!
[01/27 13:13:51 yolact.eval]: Loading model...
/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/jit/_recursive.py:165: UserWarning: 'lat_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/jit/_recursive.py:165: UserWarning: 'pred_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/jit/_recursive.py:165: UserWarning: 'downsample_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
WARNING [01/27 13:14:02 yolact.model.load]: Some parameters in the checkpoint are not used: fpn.lat_layers.0.weight, fpn.lat_layers.0.bias, fpn.lat_layers.1.weight, fpn.lat_layers.1.bias, fpn.lat_layers.2.weight, fpn.lat_layers.2.bias, fpn.pred_layers.0.weight, fpn.pred_layers.0.bias, fpn.pred_layers.1.weight, fpn.pred_layers.1.bias, fpn.pred_layers.2.weight, fpn.pred_layers.2.bias, fpn.downsample_layers.0.weight, fpn.downsample_layers.0.bias, fpn.downsample_layers.1.weight, fpn.downsample_layers.1.bias
WARNING [01/27 13:14:02 yolact.model.load]: Some parameters required by the model do not exist in the checkpoint, and are initialized as they should be: fpn_phase_1.lat_layers.0.weight, fpn_phase_1.lat_layers.0.bias, fpn_phase_1.lat_layers.1.weight, fpn_phase_1.lat_layers.1.bias, fpn_phase_1.lat_layers.2.weight, fpn_phase_1.lat_layers.2.bias, fpn_phase_2.pred_layers.0.weight, fpn_phase_2.pred_layers.0.bias, fpn_phase_2.pred_layers.1.weight, fpn_phase_2.pred_layers.1.bias, fpn_phase_2.pred_layers.2.weight, fpn_phase_2.pred_layers.2.bias, fpn_phase_2.downsample_layers.0.weight, fpn_phase_2.downsample_layers.0.bias, fpn_phase_2.downsample_layers.1.weight, fpn_phase_2.downsample_layers.1.bias
[01/27 13:14:03 yolact.eval]: Model loaded.
[01/27 13:14:03 yolact.eval]: Converting to TensorRT...
路径: data/coco/calib_images/000000002039.jpg
路径: data/coco/calib_images/000000001848.jpg
Traceback (most recent call last):
  File "eval.py", line 1328, in <module>
    "moving_statistics": None
  File "/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lsp/yolact_edge/yolact.py", line 1690, in forward
    outs = self.backbone(x)
  File "/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lsp/yolact_edge/backbone.py", line 121, in forward
    x = self.maxpool(x)
  File "/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 159, in forward
    self.return_indices)
  File "/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/_jit_internal.py", line 247, in fn
    return if_false(*args, **kwargs)
  File "/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/nn/functional.py", line 576, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: non-empty 3D or 4D input tensor expected but got ndim: 4

**Comment by haotian-liu** [comment] 2021-01-27 05:16
You did not download the calibration images for INT8 conversion. See [here](https://github.com/haotian-liu/yolact_edge/blob/master/INSTALL.md).

**Comment by haotian-liu** [comment] 2021-01-27 05:17
And please pull the newest commit of this repo to automatically convert the weights to be compatible, thanks. (with your current commit, you might need `--yolact_transfer` option).

**Comment by liangsiping2019** [comment] 2021-01-27 06:11
I Download this datasets,but the problem is still exist:
Traceback (most recent call last):
  File "eval.py", line 1328, in <module>
    "moving_statistics": None
  File "/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lsp/yolact_edge/yolact.py", line 1690, in forward
    outs = self.backbone(x)
  File "/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lsp/yolact_edge/backbone.py", line 121, in forward
    x = self.maxpool(x)
  File "/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 159, in forward
    self.return_indices)
  File "/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/_jit_internal.py", line 247, in fn
    return if_false(*args, **kwargs)
  File "/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/nn/functional.py", line 576, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: non-empty 3D or 4D input tensor expected but got ndim: 4

thank you for your help!

**Comment by haotian-liu** [comment] 2021-01-27 06:12
Can you provide the full logs and the command?

**Comment by liangsiping2019** [comment] 2021-01-27 06:15
we used four images of calib_images to test in NX box:
python eval.py --trained_model=weights/yolact_edge_54_800000.pth --benchmark --max_images=10
Config not specified. Parsed yolact_edge_config from the file name.

loading annotations into memory...
Done (t=1.59s)
creating index...
index created!
[01/27 14:09:15 yolact.eval]: Loading model...
/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/jit/_recursive.py:165: UserWarning: 'lat_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/jit/_recursive.py:165: UserWarning: 'pred_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/jit/_recursive.py:165: UserWarning: 'downsample_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
WARNING [01/27 14:09:31 yolact.model.load]: Some parameters in the checkpoint are not used: fpn.lat_layers.0.weight, fpn.lat_layers.0.bias, fpn.lat_layers.1.weight, fpn.lat_layers.1.bias, fpn.lat_layers.2.weight, fpn.lat_layers.2.bias, fpn.pred_layers.0.weight, fpn.pred_layers.0.bias, fpn.pred_layers.1.weight, fpn.pred_layers.1.bias, fpn.pred_layers.2.weight, fpn.pred_layers.2.bias, fpn.downsample_layers.0.weight, fpn.downsample_layers.0.bias, fpn.downsample_layers.1.weight, fpn.downsample_layers.1.bias
WARNING [01/27 14:09:31 yolact.model.load]: Some parameters required by the model do not exist in the checkpoint, and are initialized as they should be: fpn_phase_1.lat_layers.0.weight, fpn_phase_1.lat_layers.0.bias, fpn_phase_1.lat_layers.1.weight, fpn_phase_1.lat_layers.1.bias, fpn_phase_1.lat_layers.2.weight, fpn_phase_1.lat_layers.2.bias, fpn_phase_2.pred_layers.0.weight, fpn_phase_2.pred_layers.0.bias, fpn_phase_2.pred_layers.1.weight, fpn_phase_2.pred_layers.1.bias, fpn_phase_2.pred_layers.2.weight, fpn_phase_2.pred_layers.2.bias, fpn_phase_2.downsample_layers.0.weight, fpn_phase_2.downsample_layers.0.bias, fpn_phase_2.downsample_layers.1.weight, fpn_phase_2.downsample_layers.1.bias
[01/27 14:09:32 yolact.eval]: Model loaded.
[01/27 14:09:32 yolact.eval]: Converting to TensorRT...
路径: data/coco/calib_images/000000014312.jpg
路径: data/coco/calib_images/000000006190.jpg
路径: data/coco/calib_images/000000025853.jpg
路径: data/coco/calib_images/000000025174.jpg
Traceback (most recent call last):
  File "eval.py", line 1328, in <module>
    "moving_statistics": None
  File "/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lsp/yolact_edge/yolact.py", line 1690, in forward
    outs = self.backbone(x)
  File "/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lsp/yolact_edge/backbone.py", line 121, in forward
    x = self.maxpool(x)
  File "/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 159, in forward
    self.return_indices)
  File "/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/_jit_internal.py", line 247, in fn
    return if_false(*args, **kwargs)
  File "/home/superbox/archiconda3/envs/lsp/lib/python3.6/site-packages/torch/nn/functional.py", line 576, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: non-empty 3D or 4D input tensor expected but got ndim: 4

**Comment by haotian-liu** [comment] 2021-01-27 06:21
Can you try following two things:

(1) Evaluate without TensorRT: use `--disable_tensorrt` flag.
(2) Evaluate without calibration -- FP16 only: use `--use_fp16_tensorrt` flag.

See if the error persists and where the problem is. Also, just to clarify: did you make any modifications to the code base? or you are using the original code.

**Comment by haotian-liu** [comment] 2021-02-06 00:28
Closing the issue as the question has been answered and there is no follow-up until now. If you have any more questions or there is anything being unclear, feel free to re-open this issue and post the follow-up thread.

**Closed by haotian-liu** 2021-02-06 00:28 UTC
