### ISSUE TITLE
Can you make the model run more than 100FPS? I'm still at 8FPS, how do I run eval.py to 100FPS

### ISSUE THREAD

**Issue by LMR2018** [haotian-liu/yolact_edge#151] opened 2021-09-10 09:38 UTC
Can you make the model run more than 100FPS? I'm still at 8FPS, how do I run  eval.py to 100FPS

**Comment by haotian-liu** [comment] 2021-09-22 21:34
Duplicate of #152

**Closed** 2021-09-22 21:33 UTC
