### ISSUE TITLE
您好，为什么运行eval.py文件会进行训练？

### ISSUE THREAD

**Issue by zihan987** [haotian-liu/yolact_edge#9] opened 2020-12-27 11:19 UTC
您好，为什么运行eval.py文件会进行训练？

**Comment by haotian-liu** [comment] 2020-12-27 22:06
Please provide more details for us to understand the issue better and help you (e.g., provide logs, commands you are using, etc.)

Btw, to better benefit the community, it would be better to ask the question in English (so that others with similar questions can directly learn from this thread). Thanks.

**Comment by haotian-liu** [comment] 2020-12-29 00:45
Possibly duplicate of #3 #5

**Closed by haotian-liu** 2020-12-29 00:45 UTC
Labels: question
