### ISSUE TITLE
RuntimeError: stack expects a non-empty TensorList

### ISSUE THREAD

**Issue by QixingHuang** [haotian-liu/yolact_edge#108] opened 2021-04-23 08:37 UTC
When I run eval.py with an image, I got this error:

````
python eval.py --trained_model=yolact_edge_vid_resnet50_847_50000.pth --score_threshold=0.5 --top_k=15 --image=test_Color.jpg
Config not specified. Parsed yolact_edge_vid_resnet50_config from the file name.

[32m[04/23 16:32:27 yolact.eval]: [0mLoading model...
[32m[04/23 16:32:30 yolact.eval]: [0mModel loaded.
[32m[04/23 16:32:30 yolact.eval]: [0mConverting to TensorRT...
Traceback (most recent call last):
  File "eval.py", line 1275, in <module>
    convert_to_tensorrt(net, cfg, args, transform=BaseTransform())
  File "D:\hqx\yolact_edge\utils\tensorrt.py", line 77, in convert_to_tensorrt
    calibration_dataset = pull_calib_dataset(prev_dir)
  File "D:\hqx\yolact_edge\utils\tensorrt.py", line 67, in pull_calib_dataset
    calibration_dataset = torch.stack(images)
RuntimeError: stack expects a non-empty TensorList
````

**Comment by haotian-liu** [comment] 2021-04-27 00:08
Duplicate of #45, #90

**Closed by haotian-liu** 2021-04-27 00:08 UTC
