### ISSUE TITLE
A problem about trt on jeston agx xavier

### ISSUE THREAD

**Issue by 18lalala** [haotian-liu/yolact_edge#153] opened 2021-09-25 13:25 UTC
when loading trt
Traceback (most recent call last):
  File "eval.py", line 1275, in <module>
    convert_to_tensorrt(net, cfg, args, transform=BaseTransform())
  File "/home/puzek/yolact_edge-master/yolact_edge/utils/tensorrt.py", line 77, in convert_to_tensorrt
    calibration_dataset = pull_calib_dataset(prev_dir)
  File "/home/puzek/yolact_edge-master/yolact_edge/utils/tensorrt.py", line 67, in pull_calib_dataset
    calibration_dataset = torch.stack(images)
RuntimeError: stack expects a non-empty TensorList

**Comment by haotian-liu** [comment] 2021-09-26 23:50
Duplicate of #108.

**Closed by haotian-liu** 2021-09-26 23:50 UTC
